# Generated by Django 4.2.5 on 2023-09-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_geoposition_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoposition',
            name='cuntry',
            field=models.CharField(default=1, max_length=5, verbose_name='cuntry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geoposition',
            name='name',
            field=models.CharField(default=1, max_length=164, verbose_name='name'),
            preserve_default=False,
        ),
    ]
