# Generated by Django 4.2.5 on 2023-09-14 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_geoposition_cuntry_geoposition_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geoposition',
            old_name='cuntry',
            new_name='country',
        ),
    ]
